### ISSUE TITLE
Architecture evolution to async processing

### ISSUE THREAD

**Issue by replicadse** [voidpointergroup/spoderman#66]
## client --> server

Messages will be put into the routing service and will then be redirected to the destination service. This process is synchronous and there is no error handling or retry logic in place right now. If one of these services is unavailable, the message is discarded. \

## server --> client

Messages are sent through a redis pub/sub channel. If there is some error along the way, this will be ignored. This can only really be the case if there is no instance with the connection anymore in which case the message would be discarded anyway. Therefore, if something goes wrong along this process, we can discard the message. Also, if the instance that listens to the redis is dead, the connection and it's ID is dropped anyway, making any message delivery impossible since the IDs are new UUIDs on next client connect. Therefore, buffering in case the service is unavailable is not necessary. \
Might want to have some attachment to a DLQ anyway.

## Solution

For `client-->server` messages, the rules engine invocation as well as the destination service forward request should be wrapped inside some kind of queue consumer. If one of these fails, the message gets enqueued again (with a visibility delay for circuit breaking?). \
For `server-->client` messages, if the immediate delivery fails on the enqueue part, put the message into some dead letter sink (maybe a queue which is then persisted?).

## Tasks

- [x] Select a queue implementation for the backend.
  - [x] NATS/Jetstream
  - [ ] nsqio
- [x] Update documentation
- [x] Do the implementation changes itself
- [x] Update config file

**Comment by replicadse** [comment]
Queue implementation:
Options were Kafka, nsq, NATS and redis. Kafka is written in Java so... no way!, nsq is primarily an in-memory message delivery system which is kind of shifting the problem we try to solve instead of really solving it and redis is also best used in-memory. NATS seems to be the perfect fit for this use-case.

**Comment by replicadse** [comment]
should be done now

**Comment by replicadse** [comment]
MR merged.
